In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
arr = np.random.randint(low=1,high=51,size=10)

print("Média: ", np.mean(arr, axis=None)) 
print("Desvio Padrao: ", np.std(arr, axis=None)) 

Média:  20.4
Desvio Padrao:  12.507597691003657


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

print("array antes da raiz quadrada", arr)

arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print("array depois da raiz quadrada", arr)

array antes da raiz quadrada [0.96443103 0.51831412 0.3373504  0.96386324 0.59418651 0.81761032
 0.51638374 0.05862001 0.82513122 0.01239262]
array depois da raiz quadrada [0.96443103 0.51831412 0.58081873 0.96386324 0.59418651 0.81761032
 0.51638374 0.2421157  0.82513122 0.11132215]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3,3,3)

print("Matriz Original:", matriz)

for i in range(3):
    matriz_2d = matriz[i]   
    
    print("Matriz 2D:", matriz)
    
    max_linhas = np.amax(matriz_2d, axis=1)
    
    print("Valor máximo", max_linhas)
  

Matriz Original: [[[0.84714498 0.86642413 0.11001042]
  [0.03641569 0.59830442 0.04145083]
  [0.47742158 0.3748807  0.20211536]]

 [[0.46812032 0.23907904 0.18094043]
  [0.27665359 0.41107674 0.9861523 ]
  [0.07101822 0.76022241 0.7036343 ]]

 [[0.2866988  0.56048874 0.7911929 ]
  [0.22648627 0.30123196 0.40282257]
  [0.06533197 0.70741197 0.4471956 ]]]
Matriz 2D: [[[0.84714498 0.86642413 0.11001042]
  [0.03641569 0.59830442 0.04145083]
  [0.47742158 0.3748807  0.20211536]]

 [[0.46812032 0.23907904 0.18094043]
  [0.27665359 0.41107674 0.9861523 ]
  [0.07101822 0.76022241 0.7036343 ]]

 [[0.2866988  0.56048874 0.7911929 ]
  [0.22648627 0.30123196 0.40282257]
  [0.06533197 0.70741197 0.4471956 ]]]
Valor máximo [0.86642413 0.59830442 0.47742158]
Matriz 2D: [[[0.84714498 0.86642413 0.11001042]
  [0.03641569 0.59830442 0.04145083]
  [0.47742158 0.3748807  0.20211536]]

 [[0.46812032 0.23907904 0.18094043]
  [0.27665359 0.41107674 0.9861523 ]
  [0.07101822 0.76022241 0.7036343 ]]

 [[0.2866

### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)

print("Matriz Original:", matriz)

matriz_media = matriz.mean(0)

print("Matriz media: ", matriz_media)

matriz_final = matriz - matriz_media

print("Matriz Resultante: ", matriz_final)

Matriz Original: [[0.51735474 0.13128633 0.83884412 0.6788582  0.82628267]
 [0.64726278 0.43155528 0.04483482 0.4100589  0.15747692]
 [0.53316004 0.07187183 0.85970979 0.2492551  0.81426108]
 [0.49070907 0.93801971 0.95190738 0.91356039 0.06241978]
 [0.37818459 0.2268693  0.45645484 0.14611377 0.7552708 ]]
Matriz media:  [0.51333424 0.35992049 0.63035019 0.47956927 0.52314225]
Matriz Resultante:  [[ 0.0040205  -0.22863416  0.20849393  0.19928893  0.30314042]
 [ 0.13392854  0.07163479 -0.58551537 -0.06951037 -0.36566533]
 [ 0.01982579 -0.28804866  0.2293596  -0.23031417  0.29111883]
 [-0.02262517  0.57809922  0.32155719  0.43399112 -0.46072247]
 [-0.13514965 -0.13305119 -0.17389535 -0.3334555   0.23212855]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)

print("Matriz Original:", matriz)

diagonal = matriz.diagonal()

print("Diagonal: ", diagonal)

print("Média: ", np.mean(diagonal, axis=None)) 
print("Desvio Padrao: ", np.std(diagonal, axis=None)) 

Matriz Original: [[0.91107925 0.01509034 0.7186714  0.94492022]
 [0.20829607 0.55558252 0.26722688 0.33321706]
 [0.34145351 0.57607857 0.92431872 0.46975873]
 [0.08185199 0.88516976 0.40198674 0.58034695]]
Diagonal:  [0.91107925 0.55558252 0.92431872 0.58034695]
Média:  0.7428318600944239
Desvio Padrao:  0.17514874112232473
